steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/genuine-flight-462611-t5/my-repo/flask-app:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/genuine-flight-462611-t5/my-repo/flask-app:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - instance-groups
      - managed
      - rolling-action
      - replace
      - my-mig
      - '--version'
      - template=my-instance-template
      - '--zone=us-central1-a'
