options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SUFFIX: 'v${SHORT_SHA}'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/genuine-flight-462611-t5/my-repo/flask-app:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/genuine-flight-462611-t5/my-repo/flask-app:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-instance-template
    args:
      - compute
      - instance-templates
      - create
      - 'instance-template-${_SUFFIX}'
      - '--region=us-central1'
      - '--machine-type=e2-medium'
      - '--network=default'
      - '--subnet=default'
      - '--tags=http-server'
      - '--image-family=debian-11'
      - '--image-project=debian-cloud'
      - '--metadata=startup-script-url=gs://your-bucket/startup-script.sh'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: rolling-update
    args:
      - compute
      - instance-groups
      - managed
      - rolling-action
      - start-update
      - 'my-mig'
      - '--version=template=projects/genuine-flight-462611-t5/regions/us-central1/instanceTemplates/instance-template-${_SUFFIX}'
      - '--zone=us-central1-c'
