options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'us-central1-docker.pkg.dev/genuine-flight-462611-t5/my-repo/flask-app:latest',
        '.'
      ]

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/genuine-flight-462611-t5/my-repo/flask-app:latest'
      ]

  # Step 3: Create a new instance template with timestamp to force MIG update
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        TIMESTAMP=$(date +%s)
        gcloud compute instance-templates create instance-template-$TIMESTAMP \
          --machine-type=e2-medium \
          --image-family=debian-11 \
          --image-project=debian-cloud \
          --metadata-from-file=startup-script=startup.sh \
          --boot-disk-size=10GB \
          --boot-disk-type=pd-balanced \
          --tags=http-server

  # Step 4: Start rolling update of MIG
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        TIMESTAMP=$(date +%s)
        gcloud compute instance-groups managed rolling-action start-update my-mig \
          --version=template=global/instanceTemplates/instance-template-$TIMESTAMP \
          --zone=us-central1-c
