options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _ZONE: us-central1-c
  _REPO: my-repo
  _IMAGE: flask-app
  _PROJECT_ID: genuine-flight-462611-t5
  _MIG_NAME: my-mig

steps:
# 1. Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:latest',
      '.'
    ]

# 2. Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:latest'
    ]

# 3. Create new instance template with startup script
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - -c
    - |
      TIMESTAMP=$(date +%s)
      TEMPLATE_NAME="instance-template-$TIMESTAMP"

      gcloud compute instance-templates create "$TEMPLATE_NAME" \
        --region=${_REGION} \
        --machine-type=e2-medium \
        --network=default \
        --tags=http-server \
        --image-family=debian-11 \
        --image-project=debian-cloud \
        --metadata=startup-script="#!/bin/bash
apt update
apt install -y docker.io
systemctl start docker
systemctl enable docker
gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
docker pull us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:latest
docker stop flask-app || true
docker rm flask-app || true
docker run -d --name flask-app -p 8080:8080 us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_IMAGE}:latest" \
        && echo "$TEMPLATE_NAME" > /workspace/template-name.txt

# 4. Trigger rolling update in MIG using the new template
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - -c
    - |
      TEMPLATE_NAME=$(cat /workspace/template-name.txt)
      gcloud compute instance-groups managed rolling-action start-update ${_MIG_NAME} \
        --zone=${_ZONE} \
        --version=template=https://www.googleapis.com/compute/v1/projects/${_PROJECT_ID}/global/instanceTemplates/$TEMPLATE_NAME \
        --max-unavailable=0 \
        --max-surge=1
