options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/genuine-flight-462611-t5/my-repo/flask-app:latest',
      '.'
    ]

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/genuine-flight-462611-t5/my-repo/flask-app:latest'
    ]

  # Step 3: Trigger rolling update on MIG to rerun startup scripts
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'compute',
      'instance-groups',
      'managed',
      'rolling-action',
      'restart',
      'my-mig',
      '--zone', 'us-central1-c'
    ]
